{
    'name': 'Payroll Discount',
    'version': '1.0',
    'summary': 'Definition of the Payroll Discount',
    'description': 'Definition of the Payroll Discount',
    'author': 'Mastermind Software Services',
    'depends': ['base','mail','extenss_credit','board','sale','extenss_request'],
    'application': True,
    'website': 'https://www.mss.mx',
    'category': 'Uncategorized',
    'data': [
        'security/extenss_dn_security.xml',
        'security/ir.model.access.csv',
        # 'wizards/create_active_credit_view.xml',
        'views/credit_dn_view.xml',
        'views/credit_dn_dispersion_view.xml',
        'views/credit_dn_pre_notice_view.xml',
        'views/credit_dn_amortization_view.xml',
        'views/credit_dn_exp_notice_view.xml',
        'views/credit_dn_early_set_view.xml',
        'views/credit_dn_adv_pay_view.xml',
        'views/credit_dn_moras_view.xml',
        'views/credit_dn_acct_portfolio_view.xml',
        'views/credit_dn_payment_balance_view.xml',
        'views/credit_dn_condonation_view.xml',
        'views/credit_dn_conciliation_view.xml',
        'views/credit_dn_collection_view.xml',
        'views/credit_dn_account_view.xml',
        # 'views/credit_af_statement_account_view.xml',
        #'views/dashboard.xml',
        ],
}