{
    'name': 'Financial factoring',
    'version': '1.0',
    'summary': 'Definition of the Financial factoring',
    'description': 'Definition of the Financial factoring',
    'author': 'Mastermind Software Services',
    'depends': ['base','mail','extenss_credit','board','sale','extenss_request'],
    'application': True,
    'website': 'https://www.mss.mx',
    'category': 'Uncategorized',
    'data': [
        'security/extenss_ff_security.xml',
        'security/ir.model.access.csv',
        'views/credit_ff_view.xml',
        'views/credit_ff_lines_active_view.xml',
        'views/credit_ff_dispersion_view.xml',
        'views/credit_ff_initial_pay_view.xml',
        'views/credit_ff_pre_notice_view.xml',
        'views/credit_ff_early_set_view.xml',
        'views/credit_ff_adv_pay_view.xml',
        'views/credit_ff_moras_view.xml',
        'views/credit_ff_exp_notice_view.xml',
        'views/credit_ff_condonation_view.xml',
        'views/credit_ff_acct_portfolio_view.xml',
        'views/credit_ff_dispositions_view.xml',
        'views/credit_ff_statement_account_view.xml',
        'views/credit_ff_account_view.xml',
        'views/credit_ff_account_view.xml',
        'views/extenss_ff_portal_template.xml',
    ],
}