{
    'name': 'Pure lease',
    'version': '1.0',
    'summary': 'Definition of the Pure lease',
    'description': 'Definition of the Pure lease',
    'author': 'Mastermind Software Services',
    'depends': ['base','mail','extenss_credit','board','sale','extenss_request'],
    'application': True,
    'website': 'https://www.mss.mx',
    'category': 'Uncategorized',
    'data': [
        'security/extenss_ap_security.xml',
        'security/ir.model.access.csv',
        # 'wizards/create_active_credit_view.xml',
        'views/credit_ap_view.xml',
        'views/credit_ap_initial_pay_view.xml', 
        'views/credit_ap_pre_notice_view.xml',
        'views/credit_ap_amortization_view.xml',
        'views/credit_ap_exp_notice_view.xml',
        'views/credit_ap_early_set_view.xml',
        'views/credit_ap_adv_pay_view.xml',
        'views/credit_ap_moras_view.xml',
        'views/credit_ap_acct_portfolio_view.xml',
        'views/credit_ap_payment_balance_view.xml',
        'views/credit_ap_condonation_view.xml',
        'views/credit_ap_statement_account_view.xml',
        'views/credit_ap_account_view.xml',
        #'views/dashboard.xml',
        ],
}