{
    'name': 'Financial leasing',
    'version': '1.0',
    'summary': 'Definition of the Financial leasing',
    'description': 'Definition of the Financial leasing',
    'author': 'Mastermind Software Services',
    'depends': ['base','mail','extenss_credit','board','sale','extenss_request'],
    'application': True,
    'website': 'https://www.mss.mx',
    'category': 'Uncategorized',
    'data': [
        'security/extenss_af_security.xml',
        'security/ir.model.access.csv',
        # 'wizards/create_active_credit_view.xml',
        'views/credit_af_view.xml',
        'views/credit_af_pre_notice_view.xml',
        'views/credit_af_amortization_view.xml',
        'views/credit_af_exp_notice_view.xml',
        'views/credit_af_early_set_view.xml',
        'views/credit_af_adv_pay_view.xml',
        'views/credit_af_moras_view.xml',
        'views/credit_af_acct_portfolio_view.xml',
        'views/credit_af_payment_balance_view.xml',
        'views/credit_af_condonation_view.xml',
        'views/credit_af_statement_account_view.xml',
        'views/credit_af_account_view.xml',
        #'views/dashboard.xml',
        ],
}